### ISSUE TITLE
How to use SpritesList.json?

### ISSUE THREAD

**Issue by ZXitron** [jiangnangame/ReadPam#1]
Hello, after decoding it turns out like this, sorry, but I don't quite understand what's what. Could you explain?
To be more precise, what is **a,c,d,b** and **left, top**?
```
{
        "imageID": "zombie_pirate_basic_28x33",
        "resID": "IMAGE_ZOMBIE_ZOMBIE_PIRATE_BASIC_ZOMBIE_PIRATE_BASIC_28X33",
        "properties": {
            "width": 28,
            "height": 33,
            "a": 20,
            "c": 0,
            "b": 0,
            "d": 20,
            "left": -4.1,
            "top": -4.2
        }
}
```
And how it can be used in Adobe Flash?
Thanks

**Comment by WU-SUNFLOWER** [comment]
**a、b、c、d** mean the transformation matrix of graphic.**top** and **left** mean the transform anchor point.To know the detail information, you should read [this blog](https://plantsvszombies.fandom.com/wiki/User_blog:TimespaceLY/PAM_Format_Decryption) :).

**Comment by WU-SUNFLOWER** [comment]
And now my program can only recover PAM to JSON with plaintext datas. Recovering PAM to FLA is still a challenge for me.
